version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.16.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: npm install 
      - run:
          name: test
          command: npm run cover 
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
